<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'WP_Ultimo_WooCommerce\\Dependencies\\Pablo_Pacheco\\WP_Namespace_Autoloader\\WP_Namespace_Autoloader' => $vendorDir . '/pablo-sg-pacheco/wp-namespace-autoloader/src/WP_Namespace_Autoloader.php',
);
