<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'WP_Ultimo_WooCommerce\\Dependencies\\Pablo_Pacheco\\WP_Namespace_Autoloader\\' => array($vendorDir . '/pablo-sg-pacheco/wp-namespace-autoloader/src'),
);
