<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitc078eee57c1f0e71fae884ddd229c8fa
{
    public static $files = array (
        '7166494aeff09009178f278afd86c83f' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/load-v4p13.php',
        '27a32df4038e0d816c45760d9d757069' => __DIR__ . '/../..' . '/inc/traits/trait-singleton.php',
    );

    public static $prefixLengthsPsr4 = array (
        'W' => 
        array (
            'WP_Ultimo_WooCommerce\\Dependencies\\Pablo_Pacheco\\WP_Namespace_Autoloader\\' => 73,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'WP_Ultimo_WooCommerce\\Dependencies\\Pablo_Pacheco\\WP_Namespace_Autoloader\\' => 
        array (
            0 => __DIR__ . '/..' . '/pablo-sg-pacheco/wp-namespace-autoloader/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'WP_Ultimo_WooCommerce\\Dependencies\\Pablo_Pacheco\\WP_Namespace_Autoloader\\WP_Namespace_Autoloader' => __DIR__ . '/..' . '/pablo-sg-pacheco/wp-namespace-autoloader/src/WP_Namespace_Autoloader.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitc078eee57c1f0e71fae884ddd229c8fa::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitc078eee57c1f0e71fae884ddd229c8fa::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitc078eee57c1f0e71fae884ddd229c8fa::$classMap;

        }, null, ClassLoader::class);
    }
}
