<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitb5014b327e4bda1651b1dec74b121f29
{
    public static $files = array (
        '7166494aeff09009178f278afd86c83f' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/load-v4p13.php',
        '10e074651a40a26898dc8b21bd3ceaaa' => __DIR__ . '/../..' . '/inc/traits/trait-singleton.php',
    );

    public static $prefixLengthsPsr4 = array (
        'W' => 
        array (
            'WP_Ultimo_AffiliateWP\\Dependencies\\Pablo_Pacheco\\WP_Namespace_Autoloader\\' => 73,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'WP_Ultimo_AffiliateWP\\Dependencies\\Pablo_Pacheco\\WP_Namespace_Autoloader\\' => 
        array (
            0 => __DIR__ . '/..' . '/pablo-sg-pacheco/wp-namespace-autoloader/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'WP_Ultimo_AffiliateWP\\Dependencies\\Pablo_Pacheco\\WP_Namespace_Autoloader\\WP_Namespace_Autoloader' => __DIR__ . '/..' . '/pablo-sg-pacheco/wp-namespace-autoloader/src/WP_Namespace_Autoloader.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitb5014b327e4bda1651b1dec74b121f29::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitb5014b327e4bda1651b1dec74b121f29::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitb5014b327e4bda1651b1dec74b121f29::$classMap;

        }, null, ClassLoader::class);
    }
}
