<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit8458eeb5b4b28089bda4e2eaea38a119
{
    public static $files = array (
        '49a1299791c25c6fd83542c6fedacddd' => __DIR__ . '/..' . '/yahnis-elsts/plugin-update-checker/load-v4p11.php',
        '0f1e30274f1df4252561b365db7d3853' => __DIR__ . '/../..' . '/inc/traits/trait-singleton.php',
    );

    public static $prefixLengthsPsr4 = array (
        'W' => 
        array (
            'WP_Ultimo_Captcha\\Dependencies\\ReCaptcha\\' => 41,
            'WP_Ultimo_Captcha\\Dependencies\\Pablo_Pacheco\\WP_Namespace_Autoloader\\' => 69,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'WP_Ultimo_Captcha\\Dependencies\\ReCaptcha\\' => 
        array (
            0 => __DIR__ . '/..' . '/google/recaptcha/src/ReCaptcha',
        ),
        'WP_Ultimo_Captcha\\Dependencies\\Pablo_Pacheco\\WP_Namespace_Autoloader\\' => 
        array (
            0 => __DIR__ . '/..' . '/pablo-sg-pacheco/wp-namespace-autoloader/src',
        ),
    );

    public static $classMap = array (
        'WP_Ultimo_Captcha\\Dependencies\\Pablo_Pacheco\\WP_Namespace_Autoloader\\WP_Namespace_Autoloader' => __DIR__ . '/..' . '/pablo-sg-pacheco/wp-namespace-autoloader/src/WP_Namespace_Autoloader.php',
        'WP_Ultimo_Captcha\\Dependencies\\ReCaptcha\\ReCaptcha' => __DIR__ . '/..' . '/google/recaptcha/src/ReCaptcha/ReCaptcha.php',
        'WP_Ultimo_Captcha\\Dependencies\\ReCaptcha\\RequestMethod' => __DIR__ . '/..' . '/google/recaptcha/src/ReCaptcha/RequestMethod.php',
        'WP_Ultimo_Captcha\\Dependencies\\ReCaptcha\\RequestMethod\\Curl' => __DIR__ . '/..' . '/google/recaptcha/src/ReCaptcha/RequestMethod/Curl.php',
        'WP_Ultimo_Captcha\\Dependencies\\ReCaptcha\\RequestMethod\\CurlPost' => __DIR__ . '/..' . '/google/recaptcha/src/ReCaptcha/RequestMethod/CurlPost.php',
        'WP_Ultimo_Captcha\\Dependencies\\ReCaptcha\\RequestMethod\\Post' => __DIR__ . '/..' . '/google/recaptcha/src/ReCaptcha/RequestMethod/Post.php',
        'WP_Ultimo_Captcha\\Dependencies\\ReCaptcha\\RequestMethod\\Socket' => __DIR__ . '/..' . '/google/recaptcha/src/ReCaptcha/RequestMethod/Socket.php',
        'WP_Ultimo_Captcha\\Dependencies\\ReCaptcha\\RequestMethod\\SocketPost' => __DIR__ . '/..' . '/google/recaptcha/src/ReCaptcha/RequestMethod/SocketPost.php',
        'WP_Ultimo_Captcha\\Dependencies\\ReCaptcha\\RequestParameters' => __DIR__ . '/..' . '/google/recaptcha/src/ReCaptcha/RequestParameters.php',
        'WP_Ultimo_Captcha\\Dependencies\\ReCaptcha\\Response' => __DIR__ . '/..' . '/google/recaptcha/src/ReCaptcha/Response.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit8458eeb5b4b28089bda4e2eaea38a119::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit8458eeb5b4b28089bda4e2eaea38a119::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit8458eeb5b4b28089bda4e2eaea38a119::$classMap;

        }, null, ClassLoader::class);
    }
}
