<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'WP_Ultimo_Captcha\\Dependencies\\Pablo_Pacheco\\WP_Namespace_Autoloader\\WP_Namespace_Autoloader' => $vendorDir . '/pablo-sg-pacheco/wp-namespace-autoloader/src/WP_Namespace_Autoloader.php',
    'WP_Ultimo_Captcha\\Dependencies\\ReCaptcha\\ReCaptcha' => $vendorDir . '/google/recaptcha/src/ReCaptcha/ReCaptcha.php',
    'WP_Ultimo_Captcha\\Dependencies\\ReCaptcha\\RequestMethod' => $vendorDir . '/google/recaptcha/src/ReCaptcha/RequestMethod.php',
    'WP_Ultimo_Captcha\\Dependencies\\ReCaptcha\\RequestMethod\\Curl' => $vendorDir . '/google/recaptcha/src/ReCaptcha/RequestMethod/Curl.php',
    'WP_Ultimo_Captcha\\Dependencies\\ReCaptcha\\RequestMethod\\CurlPost' => $vendorDir . '/google/recaptcha/src/ReCaptcha/RequestMethod/CurlPost.php',
    'WP_Ultimo_Captcha\\Dependencies\\ReCaptcha\\RequestMethod\\Post' => $vendorDir . '/google/recaptcha/src/ReCaptcha/RequestMethod/Post.php',
    'WP_Ultimo_Captcha\\Dependencies\\ReCaptcha\\RequestMethod\\Socket' => $vendorDir . '/google/recaptcha/src/ReCaptcha/RequestMethod/Socket.php',
    'WP_Ultimo_Captcha\\Dependencies\\ReCaptcha\\RequestMethod\\SocketPost' => $vendorDir . '/google/recaptcha/src/ReCaptcha/RequestMethod/SocketPost.php',
    'WP_Ultimo_Captcha\\Dependencies\\ReCaptcha\\RequestParameters' => $vendorDir . '/google/recaptcha/src/ReCaptcha/RequestParameters.php',
    'WP_Ultimo_Captcha\\Dependencies\\ReCaptcha\\Response' => $vendorDir . '/google/recaptcha/src/ReCaptcha/Response.php',
);
