<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'WP_Ultimo_Plugin_And_Theme_Manager\\Dependencies\\phpDocumentor\\Reflection\\' => array($vendorDir . '/phpdocumentor/reflection-common/src', $vendorDir . '/phpdocumentor/reflection-docblock/src', $vendorDir . '/phpdocumentor/type-resolver/src'),
    'WP_Ultimo_Plugin_And_Theme_Manager\\Dependencies\\Webmozart\\Assert\\' => array($vendorDir . '/webmozart/assert/src'),
    'WP_Ultimo_Plugin_And_Theme_Manager\\Dependencies\\Prophecy\\' => array($vendorDir . '/phpspec/prophecy/src/Prophecy'),
    'WP_Ultimo_Plugin_And_Theme_Manager\\Dependencies\\Pablo_Pacheco\\WP_Namespace_Autoloader\\' => array($vendorDir . '/pablo-sg-pacheco/wp-namespace-autoloader/src'),
    'WP_Ultimo_Plugin_And_Theme_Manager\\Dependencies\\Doctrine\\Instantiator\\' => array($vendorDir . '/doctrine/instantiator/src/Doctrine/Instantiator'),
    'WP_Ultimo_Plugin_And_Theme_Manager\\Dependencies\\DeepCopy\\' => array($vendorDir . '/myclabs/deep-copy/src/DeepCopy'),
    'Symfony\\Polyfill\\Php80\\' => array($vendorDir . '/symfony/polyfill-php80'),
    'Symfony\\Polyfill\\Ctype\\' => array($vendorDir . '/symfony/polyfill-ctype'),
);
